"use client";

export default function TermsPage() {
  const line = "rgba(237,240,247,0.08)";

  const sections = [
    {
      title: "1. Service",
      body: "EasyBuilda provides a platform that lets business owners build AI-powered customer chat agents. By using EasyBuilda, you agree to these terms."
    },
    {
      title: "2. Wallet & Billing",
      body: "All payments are processed through your EasyBuilda Wallet. You top up your wallet via bank transfer (Mashreq Bank Egypt) or PayPal. Funds are credited after manual verification within 24 hours. Subscriptions (Basic $29/mo, Pro $69/mo) and pay-per-lead charges ($0.50 cold lead, $2.00 hot lead) are deducted automatically from your wallet balance. If your balance reaches zero, your AI agents are paused automatically."
    },
    {
      title: "3. Refunds",
      body: "Wallet top-ups are non-refundable once credited. If a top-up is rejected, no funds are taken. If you experience a service failure on our end, contact support and we'll credit your wallet accordingly."
    },
    {
      title: "4. Agent content",
      body: "You are responsible for the accuracy of business information you provide to train your AI agent. EasyBuilda is not liable for incorrect responses generated by your agent based on information you supplied."
    },
    {
      title: "5. Acceptable use",
      body: "You may not use EasyBuilda to deceive, mislead, or harm end users. Agents must not impersonate humans when directly asked whether they are AI. We reserve the right to suspend accounts that violate this policy."
    },
    {
      title: "6. Data",
      body: "Conversation data between your agent and visitors is stored to power lead capture and analytics. You own your data. We process it only on your behalf. See our Privacy Policy for details."
    },
    {
      title: "7. Service availability",
      body: "We aim for high availability but do not guarantee 100% uptime. Scheduled maintenance and unexpected outages may occur. We are not liable for business losses caused by downtime."
    },
    {
      title: "8. Account termination",
      body: "You may close your account at any time by contacting support. Unused wallet balance will be forfeited upon account closure. We may suspend or terminate accounts that violate these terms."
    },
    {
      title: "9. Changes",
      body: "We may update these terms. Continued use of EasyBuilda after changes constitutes acceptance of the new terms. We will notify users of material changes via email."
    },
    {
      title: "10. Contact",
      body: "For questions about these terms, email omarmaher23942@gmail.com."
    },
  ];

  return (
    <div style={{ minHeight:"100vh", background:"var(--color-void,#05070f)", color:"var(--color-starlight,#edf0f7)", fontFamily:"var(--font-sans,'Inter',sans-serif)", WebkitFontSmoothing:"antialiased" }}>
      <div aria-hidden="true" style={{ position:"fixed", inset:0, zIndex:0, pointerEvents:"none" }}>
        <div style={{ position:"absolute", top:"-15vh", right:"-8vw", width:"50vw", height:"50vh", borderRadius:"50%", background:"radial-gradient(circle,rgba(124,58,237,0.10),transparent 65%)", filter:"blur(40px)" }}/>
      </div>

      <main style={{ position:"relative", zIndex:1, maxWidth:780, margin:"0 auto", padding:"8rem 1.5rem 6rem" }}>
        <a href="/" style={{ display:"inline-flex", alignItems:"center", gap:6, marginBottom:"3rem", color:"var(--color-dust,#8891a8)", textDecoration:"none", fontSize:"0.88rem" }}
          onMouseEnter={e => (e.currentTarget.style.color="var(--color-starlight,#edf0f7)")}
          onMouseLeave={e => (e.currentTarget.style.color="var(--color-dust,#8891a8)")}>
          <svg width="14" height="14" viewBox="0 0 14 14" fill="none"><path d="M9 2L4 7l5 5" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round"/></svg>
          Back to EasyBuilda
        </a>

        <p style={{ fontFamily:"var(--font-mono,'JetBrains Mono',monospace)", fontSize:"0.7rem", textTransform:"uppercase", letterSpacing:"0.22em", color:"var(--color-nebula,#7c3aed)", marginBottom:"1rem" }}>Legal</p>
        <h1 style={{ fontFamily:"var(--font-display,'Sora',sans-serif)", fontWeight:700, fontSize:"clamp(2rem,5vw,3rem)", letterSpacing:"-0.025em", lineHeight:1.1, marginBottom:"0.5rem" }}>
          Terms of Service
        </h1>
        <p style={{ color:"var(--color-dust,#8891a8)", fontSize:"0.88rem", marginBottom:"3rem" }}>Last updated: June 2026</p>

        <div style={{ height:1, background:`linear-gradient(to right,transparent,${line} 30%,${line} 70%,transparent)`, marginBottom:"2.5rem" }}/>

        <div style={{ display:"flex", flexDirection:"column", gap:"1rem" }}>
          {sections.map(s => (
            <div key={s.title} style={{ background:"rgba(255,255,255,0.03)", border:`1px solid ${line}`, borderRadius:14, padding:"1.2rem 1.4rem" }}>
              <h3 style={{ fontFamily:"var(--font-display,'Sora',sans-serif)", fontWeight:600, fontSize:"0.97rem", color:"var(--color-starlight,#edf0f7)", marginBottom:"0.4rem" }}>{s.title}</h3>
              <p style={{ fontSize:"0.88rem", color:"var(--color-dust,#8891a8)", lineHeight:1.7, margin:0 }}>{s.body}</p>
            </div>
          ))}
        </div>

        <div style={{ marginTop:"3rem", display:"flex", gap:12, flexWrap:"wrap" }}>
          <a href="/privacy" style={{ color:"var(--color-dust,#8891a8)", fontSize:"0.88rem", textDecoration:"none" }}
            onMouseEnter={e => (e.currentTarget.style.color="var(--color-starlight,#edf0f7)")}
            onMouseLeave={e => (e.currentTarget.style.color="var(--color-dust,#8891a8)")}>Privacy Policy →</a>
          <a href="/pricing" style={{ color:"var(--color-dust,#8891a8)", fontSize:"0.88rem", textDecoration:"none" }}
            onMouseEnter={e => (e.currentTarget.style.color="var(--color-starlight,#edf0f7)")}
            onMouseLeave={e => (e.currentTarget.style.color="var(--color-dust,#8891a8)")}>Pricing →</a>
        </div>
      </main>
    </div>
  );
}